trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    cd backend
    npm install
    npm test
  displayName: 'Run Backend Test Cases'

- script: |
    cd frontend
    npm install
    npm test -- --watchAll=false
  displayName: 'Run Frontend Test Cases'